export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const FETCH_CATEGORIES_ID= "FETCH_CATEGORIES_ID";
export const ADD_CATEGORY = "ADD_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const REMOVE_CATEGORY = "REMOVE_CATEGORY";
export const UPDATE_CATE_BY_ID = "UPDATE_CATE_BY_ID";
export const STATUS_EXC = "STATUS_EXC";


export const GET_LIST_PRODUCTS = "GET_LIST_PRODUCTS";


export const GET_LIST_BRANDS = "GET_LIST_BRANDS";
export const GET_LIST_STATUS = "GET_LIST_STATUS";
export const GET_LIST_TYPES = "GET_LIST_TYPES";

export const CREATE_PRODUCTS = "CREATE_PRODUCT";
export const UPDATE_PRODUCTS = "UPDATE_PRODUCT";
export const REMOVE_PRODUCTS = "REMOVE_PRODUCT";

export const CURENT_PAGE = "CURENT_PAGE";
export const LIMIT_ITEM = "LIMIT_ITEM";